### ISSUE TITLE
BF AV8B Profile Right MPD - Gain Rocker non-functional

### ISSUE THREAD

**Issue by BlueFinBima** [HeliosProfiles/DCS-AV-8B-NA-Profile-BlueFinBima#1]
Originally raised by @MadKreator37 in the wrong repo under https://github.com/HeliosVirtualCockpit/Helios/issues/820.

If you are having problems installing / configuring / using a profile then you should use the support process for the provider of that profile.

- [ x] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)
---
### Describe the Helios Issue

Right MPD Gain rocker has no Input, Output, or graphical changes when pressed.

 - Helios Version 1.6.6070.0002
 - DCS Version 2.9.3.57104

### The problem happened while using 
(place an 'x' between the square brackets for all that apply)
 - [ ] Profile Editor
 - [ x] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

**Comment by BlueFinBima** [comment]
@MadKreator37 Is this just a case of the images being a little awkward, or does your rocker work differently from this video?  If the issue is really that the gain on the MFD image does not change, then I believe that only certain displays have a gain adjustment.  

Let me know if your functionality does not match the video (I had to speed this up to get the video to be an acceptable size for GitHub)

https://github.com/HeliosProfiles/DCS-AV-8B-NA-Profile-BlueFinBima/assets/18526232/adee7008-76e5-487f-bff1-05816f19627c

**Comment by MadKreator37** [comment]
On mine the switch itself doesn't even react to pushing it. Input or output. The switch itself is stuck on the "center" image. I will delete and reinstall. Maybe mine just has a hiccup.

**Comment by BlueFinBima** [comment]
I think that rocker is a swipe rather than a push

**Comment by BlueFinBima** [comment]
The Right MPD used in the profile is part of the "Front Cockpit" mega-gauge, and the flight instruments (also part of the same gauge) has a transparent part of its background image overlaying the gain button on the right MPD causing it to become unusable.  [949b90c](https://github.com/HeliosVirtualCockpit/Helios/commit/949b90c66d23dfab3b349c60ddb64741d4699e74) reorders the Right MPD to be in front of the Flight Instruments.  This fix is most likely to ship in Helios 1.6.608.

**Comment by MadKreator37** [comment]
Excellent! You rock Mr. Bluefin!

**Comment by BlueFinBima** [comment]
Flagged as Won't Fix because changing this profile makes little sense when the problem will get fixed in Helios.
